Add support for kernel lock analysis
intel/PerfSpect pull request #114
Opened 2024-12-06 06:44 UTC by TianyouLi

As system contains more and more cores, it would be usuful to be able to analyze the kernel lock overhead that impact the overall system scalability. Here added the perfspect lock comment to collect system wide hotspot, c2c and lock contention information, that will be helpful experienced performance engineers to have a chance to look into lock related problems.

Example Command:

- ./perfspect lock
   
   collect hotspot, c2c and lock contention at the whole system in 10 seconds, with sample frequency as 11

- ./perfspect lock --duration 30 --frequency 99
  
   collect hotspot, c2c and lock contention at the whole system in 30 seconds, with sample frequency as 99

Example Output:

The output will be the perf command output with text format.

![image](https://github.com/user-attachments/assets/a8b646ee-dde8-44e9-bd8e-f8d3eefd6649)

![image](https://github.com/user-attachments/assets/2ba0728b-6253-4a6e-af28-93dc2811977d)

![image](https://github.com/user-attachments/assets/e47ea225-f126-49b4-af10-327153248ffa)

![image](https://github.com/user-attachments/assets/d7a58f57-1772-413f-bd51-6a60671e7ae3)

2024-12-06 21:25 UTC, harp-intel requested changes
Code looks very good. I left minor suggestions inline.

- Please update README.md in the project's root directory to include the 'lock' command (similar to other commands).

- Currently, only the txt report is readable. Please add an HTML renderer for equivalent readability. 
We can consider other formats and more report format improvements in the future. Ideally, we will add Insights to help interpret the large amount of data presented to the user.

- The Lock Contention field isn't working for me. Likely due to the build/version of perf being used by PerfSpect. See tools/Makefile.
```
Lock Contention:                Error: switch `b' is not available because no BUILD_BPF_SKEL=1
 Usage: perf lock contention [<options>]

    -b, --use-bpf         use BPF program to collect lock contention stats
                          (not built-in because no BUILD_BPF_SKEL=1)
```

2024-12-06 21:25 UTC, harp-intel commented on internal/script/script_defs.go
> +# PERF_C2C_PID=$!
Can these three commented lines be removed?

2024-12-06 21:25 UTC, harp-intel commented on internal/script/script_defs.go
> +# wait ${PERF_C2C_PID}
Can this commented line be removed?

2024-12-06 21:25 UTC, harp-intel commented on internal/report/table_defs.go
> +		{Name: "Cache2Cache with    CallStack", Values: []string{sectionValueFromOutput(outputs, "perf_c2c_callgraph")}},
Please remove extra spaces in "with" field names.

2024-12-06 21:25 UTC, harp-intel commented on internal/report/table_defs.go
> +		//HTMLTableRendererFunc: kernelLockAnalysisHTMLRenderer
Remove commented line or implement renderer.

2024-12-08 01:54 UTC, TianyouLi commented
@harp-intel very appreciated for your review! I will resolve all your suggestions in the coming days and add test cases accordingly. 

Regarding to the perf lock contention, you are right, the -b option might not be supported. I should check the capability and by pass the perf lock contention if the feature missing on perf. 

Thanks.

2024-12-08 04:40 UTC, TianyouLi commented on internal/report/table_defs.go
> +		//HTMLTableRendererFunc: kernelLockAnalysisHTMLRenderer
_done_

2024-12-08 04:40 UTC, TianyouLi commented on internal/report/table_defs.go
> +		{Name: "Cache2Cache with    CallStack", Values: []string{sectionValueFromOutput(outputs, "perf_c2c_callgraph")}},
done

2024-12-08 04:40 UTC, TianyouLi commented on internal/script/script_defs.go
> +# wait ${PERF_C2C_PID}
done

2024-12-08 04:44 UTC, TianyouLi commented on internal/script/script_defs.go
> +# PERF_C2C_PID=$!
done

2024-12-08 04:49 UTC, TianyouLi commented
You are definitely right on the report part. I'd like to further improve it based on the feedbacks and also my personal experiences. For example, it's possible to see the lock cycle overall percentage and the lock cycle distribution with call stacks. The off-cpu analysis is also very useful when combined with lock contention information. As you pointed out, it could be further improvement on the reporting part, right now we just begin with a very rough feature that useable but not quite convenient.

2024-12-09 01:28 UTC, harp-intel commented
@TianyouLi  Well done. I appreciate the updates.

PerfSpect builds and packages a specific version of perf. This perf doesn't support the bpf option. So, let's try to make PerfSpect build and use perf that has the required bpf support.

2024-12-09 03:24 UTC, TianyouLi commented
> @TianyouLi Well done. I appreciate the updates.
> 
> PerfSpect builds and packages a specific version of perf. This perf doesn't support the bpf option. So, let's try to make PerfSpect build and use perf that has the required bpf support.

It should work with BUILD_BPF_SKEL=1 in tools/perf makefile tools/Makefile (make LDFLAGS="-static --static"  BUILD_BPF_SKEL=1). The problem is I can not test it in my environment, I've never get the full build environment work correctly. 

I checked with the source, the current version of perf has already contains the support on BPF. But it relies on the build environment a lot to enable it. 

![image](https://github.com/user-attachments/assets/75cda394-4e86-4b78-85eb-364d5a360b54)

![image](https://github.com/user-attachments/assets/a4094113-b23c-4a5a-8e12-07a2a506e151)

Since this feature could survive without perf lock contention -bv, would it be possible to have this feature merged and then deal with the perf tool issue?

2024-12-09 03:28 UTC, TianyouLi commented
@harp-intel, on my dev box without any perfspect related , i tried the perf build with make LDFLAGS="-static --static" BUILD_BPF_SKEL=1, the following error appears. I don't think my build environment is aligned with yours.

![image](https://github.com/user-attachments/assets/6c854b86-06cb-4f8e-b13b-62761d3525cc)

2024-12-09 05:45 UTC, TianyouLi commented
> Code looks very good. I left minor suggestions inline.
> 
> * Please update README.md in the project's root directory to include the 'lock' command (similar to other commands).
> * Currently, only the txt report is readable. Please add an HTML renderer for equivalent readability.
>   We can consider other formats and more report format improvements in the future. Ideally, we will add Insights to help interpret the large amount of data presented to the user.
> * The Lock Contention field isn't working for me. Likely due to the build/version of perf being used by PerfSpect. See tools/Makefile.
> 
> ```
> Lock Contention:                Error: switch `b' is not available because no BUILD_BPF_SKEL=1
>  Usage: perf lock contention [<options>]
> 
>     -b, --use-bpf         use BPF program to collect lock contention stats
>                           (not built-in because no BUILD_BPF_SKEL=1)
> ```

https://github.com/intel/PerfSpect/actions/runs/12229325293/job/34108928079?pr=116

It's not a hard dependencies. Would it be possible to merge this feature first?

2024-12-10 21:07 UTC, harp-intel approved these changes

2024-12-10 21:08 UTC, merged